import React from "react";
import PagePrisma from "@/components/common/prisma/prisma";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Prisma",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <>
            <PagePrisma/>
        </>
    );
}
