import React from "react";
import PageYouTube from "@/components/common/youtube/youtube";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Youtube",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <>
            <PageYouTube/>
        </>
    );
}
