import React from "react";
import PageCounter from "@/components/common/counter/counter";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Counter",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <>
            <PageCounter/>
        </>
    );
};
