import React from "react";
// import PageTodo from "@/components/common/todo/todo";
import TodoForm from "@/components/common/todo/TodoForm";
import Todos from "@/components/common/todo/Todos";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Todo List",
    description: "Generated by create next app",
};

const Page = () => {
    return (
        <div className="max-w-lg m-auto w-full mt-8">
            <TodoForm/>
            <Todos/>
        </div>
    );
}

export default Page;
