import React from "react";
import PageTodo from "@/components/common/todo/todo";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Todo List",
    description: "Generated by create next app",
};

const Page = () => {
    return (
        <>
            <PageTodo/>
        </>
    );
}

export default Page;
